// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    int n=Integer.parseInt(args[0]);
		double bigger=0.0;
		double smaller=0.0;
		double Ratio;
		while (n>0) 
		{
			double rnd= Math.random();
			if (rnd>0.5) 
			{
				bigger=bigger+1.0;
			}
			else smaller=smaller+1.0;
			n--;
		}
		if (smaller!=0) 
		{
			System.out.println("> 0.5: "+(int)bigger+" times");
			System.out.println("<= 0.5: "+(int)smaller+" times");
			Ratio=bigger/smaller;
			if (Ratio>1) 
			{
				System.out.println("Ratio: "+1/Ratio);
			}
			else
			System.out.println("Ratio: "+Ratio);	
		}
		else 
		{
			System.out.println("> 0.5: "+(int)bigger+" times");
			System.out.println("<= 0.5: "+(int)smaller+" times");
			System.out.println("Ratio: 0");
		}
	}
}
